version: '3.8'

services:
  api:
    build: 
      context: . 
      dockerfile: Dockerfile
    #image: paolagarcia02/workshop-api:v1
    ports:
      - "8407:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SaviaVetdb=Server=mysql;Port=3306;Database=SaviaVetdb;Uid=root;Pwd=DockerMysql1#;
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "8507:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=DockerMysql1#
      - MYSQL_DATABASE=SaviaVetdb
    volumes:
      - BbDdScripts:/var/lib/mysql
      - ./BbDdScripts:/docker-entrypoint-initdb.d/
    

volumes:
  BbDdScripts: